esphome:
  name: my-esp32-s3

esp32:
  board: esp32-s3-devkitc-1  # 这是最通用的 S3 板型
  framework:
    type: arduino  # S3 建议配合 arduino 框架使用，兼容性最好

# 开启日志，S3 默认通常通过 USB 串口输出
logger:
  hardware_uart: USB_SERIAL_JTAG  # 关键：S3 很多板子日志是通过内置 USB 输出的

# 开启网页服务
web_server:
  port: 80

wifi:
  ssid: "IM-1601"
  password: "asdfghjkl;'"

api:
  encryption:
    key: "V7HED0Y55UoteVj974gw6EpWWzDFufqJMpJs/XxRbKg="

ota:
  - platform: esphome
