esphome:
  name: air-quality-pms5003s
  friendly_name: "空气质量监测仪"

# 核心修改处：指定正确的开发板型号
esp32:
  board: esp32-s3-devkitc-1  # 【关键修改】使用ESP32-S3的开发板标识
  framework:
    type: arduino

# 开启 Web 页面服务
web_server:
  port: 80
  include_internal: true

web_server_base:

logger:
  level: INFO

# WiFi配置
wifi:
  ssid: "IM-1601"
  password: "asdfghjkl;'"

api:
  encryption:
    key: "V7HED0Y55UoteVj974gw6EpWWzDFufqJMpJs/XxRbKg="

ota:
  - platform: esphome
    password: "qwe@1234" # 请务必使用一个强密码

# ========== 硬件接口配置 ==========
uart:
  id: uart_pms
  tx_pin: GPIO1
  rx_pin: GPIO2
  baud_rate: 9600
  rx_buffer_size: 512

i2c:
  sda: GPIO5
  scl: GPIO4
  scan: true

# ========== 传感器配置 ==========
sensor:
  - platform: pmsx003
    uart_id: uart_pms
    type: PMS5003S
    update_interval: 30s
    pm_1_0:
      name: "PM1.0"
      id: pm10_sensor
    pm_2_5:
      name: "PM2.5"
      id: pm25_sensor
      filters:
        - sliding_window_moving_average: # 增加平滑滤波，数据不跳变
            window_size: 5
            send_every: 1
    pm_10_0:
      name: "PM10"
      id: pm100_sensor
    # 甲醛传感器换算修改
    formaldehyde:
      name: "HCHO 甲醛"
      id: hcho_sensor
      unit_of_measurement: "mg/m³"
      accuracy_decimals: 3
      filters:
        - multiply: 0.001
# ========== 字体定义 ==========
font:
  - file: "gfonts://Roboto"
    id: font_roboto12
    size: 12
# ========== OLED 显示屏配置 ==========
display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    lambda: |-
      it.printf(0, 0, id(font_roboto12), "Air Quality Station");
      
      // PM2.5 显示及等级提示
      if (id(pm25_sensor).has_state()) {
        it.printf(0, 15, id(font_roboto12), "PM2.5: %.0f ug/m3", id(pm25_sensor).state);
      
      if (id(pm100_sensor).has_state()) {
        it.printf(0, 30, id(font_roboto12), "PM10 : %.0f ug/m3", id(pm100_sensor).state);
      }
      
      if (id(hcho_sensor).has_state()) {
        it.printf(0, 45, id(font_roboto12), "HCHO : %.3f mg/m3", id(hcho_sensor).state);
      } else {
        it.printf(0, 45, id(font_roboto12), "HCHO : Warming up...");
      }
